# Generated by Django 5.2 on 2025-05-13 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='poste',
            fields=[
                ('id_poste', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('contenue', models.CharField(max_length=2000)),
                ('nombre_jaime', models.IntegerField(default=0)),
                ('nombre_commentaire', models.IntegerField(default=0)),
                ('nombre_republication', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('author_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('likes_video', models.IntegerField()),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, max_length=100)),
                ('media_url', models.TextField(default='')),
                ('comment_id', models.CharField(db_index=True, max_length=100)),
                ('commenter_id', models.CharField(db_index=True, max_length=100)),
                ('comment_text', models.TextField()),
                ('comment_likes', models.IntegerField(default=0)),
                ('post_likes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('post_id', 'comment_id')},
            },
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('texte', models.CharField(max_length=2000)),
                ('id_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraping.poste')),
            ],
        ),
    ]
