# Generated by Django 5.2 on 2025-05-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='twittercomment',
            index=models.Index(fields=['tweet_id'], name='scraping_tw_tweet_i_a5a787_idx'),
        ),
    ]
