# Generated by Django 4.2.20 on 2025-05-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Demo',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sentiment', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
